package phd2

import (
	"bufio"
	"encoding/json"
	"fmt"
	"image"
	"net"
	"sync"

	"github.com/pkg/errors"
)

// RPCClient is the full featured client to use for interfacing with PHD2.
type RPCClient struct {
	d    Dialer
	conn net.Conn

	reader *bufio.Reader
	writer *bufio.Writer

	// Ensures only one RPC method call is active at a time.
	methodMutex    sync.Mutex
	methodResponse chan []byte
	requestID      int

	eventsMutex sync.Mutex
	events      chan interface{}
}

// NewRPCClient creates a new RPCClient.
func NewRPCClient(d Dialer) *RPCClient {
	return &RPCClient{
		d: d,
	}
}

// Connect connects to the PHD2 RPC server at the given host and port. This is
// normally port 4400, 4401, etc.
func (c *RPCClient) Connect(host string, port int) error {
	var err error

	c.conn, err = c.d.Dial("tcp", fmt.Sprintf("%s:%d", host, port))
	if err != nil {
		return errors.Wrap(err, "error connecting to phd2")
	}

	c.methodResponse = make(chan []byte, 1)

	c.reader = bufio.NewReader(c.conn)
	c.writer = bufio.NewWriter(c.conn)

	go c.readLoop()

	return nil
}

// Close disconnects from the PHD2 RPC server.
func (c *RPCClient) Close() error {
	err := c.conn.Close()
	if err != nil {
		return errors.Wrap(err, "error closing connection")
	}

	c.conn = nil
	close(c.methodResponse)

	c.reader = nil
	c.writer = nil

	return nil
}

// Subscribe returns a channel that can be used to receive all the events
// generated by PHD2. The caller should NOT close this channel. Call
// Unsubscribe to stop receiving these events.
func (c *RPCClient) Subscribe() (<-chan interface{}, error) {
	c.eventsMutex.Lock()
	defer c.eventsMutex.Unlock()

	if c.events != nil {
		return nil, errors.New("already subscribed")
	}

	c.events = make(chan interface{})

	return c.events, nil
}

// Unsubscribe closes the events channel.
func (c *RPCClient) Unsubscribe() error {
	c.eventsMutex.Lock()
	defer c.eventsMutex.Unlock()

	if c.events == nil {
		return errors.New("not subscribed")
	}

	close(c.events)
	c.events = nil

	return nil
}

func (c *RPCClient) readLoop() {
	var line []byte
	var partial bool
	var err error

	for {
		var bytes []byte

		bytes, partial, err = c.reader.ReadLine()
		if err != nil {
			// TODO: Handle errors properly.
			println(err.Error())
			return
		}

		line = append(line, bytes...)

		if !partial {
			err = c.processEvent(line)
			if err != nil {
				// TODO: Handle errors properly.
				println(err.Error())
			}
			line = nil
		}
	}
}

func (c *RPCClient) processEvent(line []byte) error {
	var evt Event
	err := json.Unmarshal(line, &evt)
	if err != nil {
		return errors.Wrap(err, "error unmarshalling event")
	}

	resp, ok := getEvent(evt.Event)
	if !ok {
		if len(evt.Event) != 0 {
			return errors.Wrap(err, "unknown event")
		}

		c.methodResponse <- line
		return nil
	}

	err = json.Unmarshal([]byte(line), resp)
	if err != nil {
		return errors.Wrap(err, "error unmarshalling event")
	}

	c.eventsMutex.Lock()
	if c.events != nil {
		c.events <- resp
	}
	c.eventsMutex.Unlock()

	return nil
}

type rpcRequest struct {
	Method string        `json:"method"`
	ID     int           `json:"id"`
	Params []interface{} `json:"params,omitempty"`
}

type rpcError struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type rpcResponse struct {
	ID     int             `json:"id"`
	Error  rpcError        `json:"error,omitempty"`
	Result json.RawMessage `json:"result"`
}

func (c *RPCClient) call(name string, params []interface{}, result interface{}) (*rpcResponse, error) {
	c.methodMutex.Lock()
	defer c.methodMutex.Unlock()

	c.requestID++

	req := rpcRequest{
		Method: name,
		ID:     c.requestID,
		Params: params,
	}

	bytes, err := json.Marshal(&req)
	if err != nil {
		return nil, errors.Wrap(err, "error marshalling request")
	}

	bytes = append(bytes, '\r', '\n')

	_, err = c.writer.Write(bytes)
	if err != nil {
		return nil, errors.Wrap(err, "error writing to connection")
	}

	err = c.writer.Flush()
	if err != nil {
		return nil, errors.Wrap(err, "error flushing write")
	}

	line := <-c.methodResponse

	var resp rpcResponse

	err = json.Unmarshal(line, &resp)
	if err != nil {
		return nil, errors.Wrap(err, "error unmarshalling response")
	}

	if resp.ID != req.ID {
		return nil, errors.New("incorrect response received")
	}

	err = json.Unmarshal(resp.Result, result)

	return &resp, errors.Wrap(err, "error unmarshalling result")
}

// https://github.com/OpenPHDGuiding/phd2/wiki/EventMonitoring#available-methods
// https://github.com/OpenPHDGuiding/phd2/blob/master/event_server.cpp

func (c *RPCClient) GetExposure() (int, error) {
	var result int
	_, err := c.call("get_exposure", nil, &result)
	return result, errors.Wrap(err, "error calling jsonrpc method")
}

func (c *RPCClient) CaptureSingleFrame(duration int, subframe []int) error {
	var result int
	_, err := c.call("capture_single_frame", []interface{}{duration, subframe}, &result)
	return errors.Wrap(err, "error calling jsonrpc method")
}

func (c *RPCClient) ClearCalibration(which string) error {
	var result int
	_, err := c.call("clear_calibration", []interface{}{which}, &result)
	return errors.Wrap(err, "error calling jsonrpc method")
}

type Settle struct {
	Pixels         float64 `json:"pixels"`
	TimeSeconds    int     `json:"time"`
	TimeoutSeconds int     `json:"timeout"`
}

func (c *RPCClient) Dither(pixels float64, raOnly bool, settle Settle) error {
	var result int
	_, err := c.call("dither", []interface{}{pixels, raOnly, settle}, &result)
	return errors.Wrap(err, "error calling jsonrpc method")
}

func (c *RPCClient) FindStar() ([]float64, error) {
	var result []float64
	_, err := c.call("find_star", nil, &result)
	return result, errors.Wrap(err, "error calling jsonrpc method")
}

func (c *RPCClient) FlipCalibration() error {
	var result int
	_, err := c.call("flip_calibration", nil, &result)
	return errors.Wrap(err, "error calling jsonrpc method")
}

func (c *RPCClient) GetAppState() (string, error) {
	var result string
	_, err := c.call("get_app_state", nil, &result)
	return result, errors.Wrap(err, "error calling jsonrpc method")
}

func (c *RPCClient) GetCalibrated() (bool, error) {
	var result bool
	_, err := c.call("get_calibrated", nil, &result)
	return result, errors.Wrap(err, "error calling jsonrpc method")
}

func (c *RPCClient) GetConnected() (bool, error) {
	var result bool
	_, err := c.call("get_connected", nil, &result)
	return result, errors.Wrap(err, "error calling jsonrpc method")
}

func (c *RPCClient) GetAlgorithmParamNames(axis string) ([]string, error) {
	var result []string
	_, err := c.call("get_algo_param_names", []interface{}{axis}, &result)
	return result, errors.Wrap(err, "error calling jsonrpc method")
}

func (c *RPCClient) GetAlgorithmParam(axis, param string) (float64, error) {
	var result float64
	_, err := c.call("get_algo_param", []interface{}{axis, param}, &result)
	return result, errors.Wrap(err, "error calling jsonrpc method")
}

type CalibrationData struct {
	Calibrated bool    `json:"calibrated"`
	XAngle     float64 `json:"xAngle"`
	XRate      float64 `json:"xRate"`
	XParity    string  `json:"xParity"`
	YAngle     float64 `json:"yAngle"`
	YRate      float64 `json:"yRate"`
	YParity    string  `json:"yParity"`
}

func (c *RPCClient) GetCalibrationData(which string) (CalibrationData, error) {
	var result CalibrationData
	_, err := c.call("get_calibration_data", []interface{}{which}, &result)
	return result, errors.Wrap(err, "error calling jsonrpc method")
}

type CoolerStatus struct {
	Temperature float64 `json:"temperature"`
	CoolerOn    bool    `json:"coolerOn"`
	Setpoint    float64 `json:"setpoint"`
	Power       float64 `json:"power"`
}

func (c *RPCClient) GetCoolerStatus() (CoolerStatus, error) {
	var result CoolerStatus
	_, err := c.call("get_cooler_status", nil, &result)
	return result, errors.Wrap(err, "error calling jsonrpc method")
}

type Equipment struct {
	Name      string `json:"name"`
	Connected bool   `json:"connected"`
}

type CurrentEquipment struct {
	Camera   Equipment `json:"camera"`
	Mount    Equipment `json:"mount"`
	AuxMount Equipment `json:"aux_mount"`
	AO       Equipment `json:"AO"`
	Rotator  Equipment `json:"rotator"`
}

func (c *RPCClient) GetCurrentEquipment() (CurrentEquipment, error) {
	var result CurrentEquipment
	_, err := c.call("get_current_equipment", nil, &result)
	return result, errors.Wrap(err, "error calling jsonrpc method")
}

func (c *RPCClient) GetDecGuidMode() (string, error) {
	var result string
	_, err := c.call("get_dec_guide_mode", nil, &result)
	return result, errors.Wrap(err, "error calling jsonrpc method")
}

func (c *RPCClient) GetExposureDurations() ([]int, error) {
	var result []int
	_, err := c.call("get_exposure_durations", nil, &result)
	return result, errors.Wrap(err, "error calling jsonrpc method")
}

func (c *RPCClient) GetLockPosition() ([]int, error) {
	var result []int
	_, err := c.call("get_lock_position", nil, &result)
	return result, errors.Wrap(err, "error calling jsonrpc method")
}

func (c *RPCClient) GetLockShiftEnabled() (bool, error) {
	var result bool
	_, err := c.call("get_lock_shift_enabled", nil, &result)
	return result, errors.Wrap(err, "error calling jsonrpc method")
}

type LockShiftParams struct {
	Enabled bool      `json:"enabled"`
	Rate    []float64 `json:"rate"`
	Units   string    `json:"units"`
	Axes    string    `json:"axes"`
}

func (c *RPCClient) GetLockShiftParams() (LockShiftParams, error) {
	var result LockShiftParams
	_, err := c.call("get_lock_shift_params", nil, &result)
	return result, errors.Wrap(err, "error calling jsonrpc method")
}

func (c *RPCClient) GetPaused() (bool, error) {
	var result bool
	_, err := c.call("get_paused", nil, &result)
	return result, errors.Wrap(err, "error calling jsonrpc method")
}

func (c *RPCClient) GetPixelScale() (float64, error) {
	var result float64
	_, err := c.call("get_pixel_scale", nil, &result)
	return result, errors.Wrap(err, "error calling jsonrpc method")
}

type Profile struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

func (c *RPCClient) GetProfile() (Profile, error) {
	var result Profile
	_, err := c.call("get_profile", nil, &result)
	return result, errors.Wrap(err, "error calling jsonrpc method")
}

func (c *RPCClient) GetProfiles() ([]Profile, error) {
	var result []Profile
	_, err := c.call("get_profiles", nil, &result)
	return result, errors.Wrap(err, "error calling jsonrpc method")
}

func (c *RPCClient) GetSearchRegion() (int, error) {
	var result int
	_, err := c.call("get_search_region", nil, &result)
	return result, errors.Wrap(err, "error calling jsonrpc method")
}

func (c *RPCClient) GetSensorTemperature() (float64, error) {
	var result float64
	_, err := c.call("get_sensor_temperature", nil, &result)
	return result, errors.Wrap(err, "error calling jsonrpc method")
}

type StarPosition struct {
	X int `json:"X"`
	Y int `json:"Y"`
}

type StarImage struct {
	Frame   int          `json:"frame"`
	Width   int          `json:"width"`
	Height  int          `json:"height"`
	StarPos StarPosition `json:"star_pos"`
	Pixels  string       `json:"pixels"`
	Image   image.Image
}

func (c *RPCClient) GetStarImage(maxSize int) (StarImage, error) {
	var result StarImage

	var params []interface{}

	if maxSize > 0 {
		params = []interface{}{maxSize}
	}

	_, err := c.call("get_star_image", params, &result)
	if err != nil {
		return result, errors.Wrap(err, "error calling jsonrpc method")
	}

	return result, nil
	/*
		bytes, err := base64.RawStdEncoding.DecodeString(result.Pixels)
		if err != nil {
			return result, errors.Wrap(err, "error decoding image pixels")
		}

		// TODO: Turn bytes into an image object.

		return result, nil
	*/
}

func (c *RPCClient) GetUseSubframes() (bool, error) {
	var result bool
	_, err := c.call("get_use_subframes", nil, &result)
	return result, errors.Wrap(err, "error calling jsonrpc method")
}

func (c *RPCClient) Guide(settle Settle, recalibrate bool) error {
	var result int
	_, err := c.call("guide", []interface{}{settle, recalibrate}, &result)
	return errors.Wrap(err, "error calling jsonrpc method")
}

func (c *RPCClient) GuidePulse(amount int, direction, which string) error {
	var result int
	_, err := c.call("guide_pulse", []interface{}{amount, direction, which}, &result)
	return errors.Wrap(err, "error calling jsonrpc method")
}

func (c *RPCClient) Loop() error {
	var result int
	_, err := c.call("loop", nil, &result)
	return errors.Wrap(err, "error calling jsonrpc method")
}

func (c *RPCClient) SaveImage() (string, error) {
	var result struct {
		Filename string `json:"filename"`
	}
	_, err := c.call("save_image", nil, &result)
	return result.Filename, errors.Wrap(err, "error calling jsonrpc method")
}

func (c *RPCClient) SetAlgorithmParam(axis, name string, value float64) error {
	var result int
	_, err := c.call("set_algo_param", []interface{}{axis, name, value}, &result)
	return errors.Wrap(err, "error calling jsonrpc method")
}

func (c *RPCClient) SetConnected(connect bool) error {
	var result int
	_, err := c.call("set_connected", []interface{}{connect}, &result)
	return errors.Wrap(err, "error calling jsonrpc method")
}

func (c *RPCClient) SetDecGuideMode(mode string) error {
	var result int
	_, err := c.call("set_dec_guide_mode", []interface{}{mode}, &result)
	return errors.Wrap(err, "error calling jsonrpc method")
}

func (c *RPCClient) SetExposure(length int) error {
	var result int
	_, err := c.call("set_exposure", []interface{}{length}, &result)
	return errors.Wrap(err, "error calling jsonrpc method")
}

func (c *RPCClient) SetLockPosition(x, y float64, exact bool) error {
	var result int
	_, err := c.call("set_lock_position", []interface{}{x, y, exact}, &result)
	return errors.Wrap(err, "error calling jsonrpc method")
}

func (c *RPCClient) SetLockShiftEnabled(enable bool) error {
	var result int
	_, err := c.call("set_lock_shift_enabled", []interface{}{enable}, &result)
	return errors.Wrap(err, "error calling jsonrpc method")
}

func (c *RPCClient) SetLockShiftParams(params LockShiftParams) error {
	var result int
	_, err := c.call("set_lock_shift_params", []interface{}{params}, &result)
	return errors.Wrap(err, "error calling jsonrpc method")
}

func (c *RPCClient) SetPaused(paused, full bool) error {
	var result int

	params := []interface{}{paused}
	if full {
		params = append(params, "full")
	}

	_, err := c.call("set_paused", params, &result)
	return errors.Wrap(err, "error calling jsonrpc method")
}

func (c *RPCClient) SetProfile(id int) error {
	var result int
	_, err := c.call("set_profile", []interface{}{id}, &result)
	return errors.Wrap(err, "error calling jsonrpc method")
}

func (c *RPCClient) Shutdown() error {
	var result int
	_, err := c.call("shutdown", nil, &result)
	return errors.Wrap(err, "error calling jsonrpc method")
}

func (c *RPCClient) StopCapture() error {
	var result int
	_, err := c.call("stop_capture", nil, &result)
	return errors.Wrap(err, "error calling jsonrpc method")
}
